// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-BmfWLFrsKpCZKtTC4ObSVYX8Zd7xc4',
    appId: '1:271838805042:web:595908c3ce30986eb8902b',
    messagingSenderId: '271838805042',
    projectId: 'dukandarapp-e171a',
    authDomain: 'dukandarapp-e171a.firebaseapp.com',
    storageBucket: 'dukandarapp-e171a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTI00E3UtcYJZ9NXnp_L03Gn0aDD4pAJM',
    appId: '1:271838805042:android:273dbd91c2ebcf8bb8902b',
    messagingSenderId: '271838805042',
    projectId: 'dukandarapp-e171a',
    storageBucket: 'dukandarapp-e171a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApks983r2SAK5orXPlQK8gKHJhPkcnb8',
    appId: '1:271838805042:ios:0f3abe017b2609c1b8902b',
    messagingSenderId: '271838805042',
    projectId: 'dukandarapp-e171a',
    storageBucket: 'dukandarapp-e171a.appspot.com',
    iosClientId: '271838805042-th591th80qnke63ctthg2qbva8etehkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.haradhaniyaSeller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApks983r2SAK5orXPlQK8gKHJhPkcnb8',
    appId: '1:271838805042:ios:ab4566d91f3a50eab8902b',
    messagingSenderId: '271838805042',
    projectId: 'dukandarapp-e171a',
    storageBucket: 'dukandarapp-e171a.appspot.com',
    iosClientId: '271838805042-nbfs87lrv7v4dooalsck9404ndrn40tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.haradhaniyaSeller1.RunnerTests',
  );
}
